config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :stocks, only: [:update]

  
  root "pages#home"
  get "search_stock", to: "stocks#search"
  get "search_user", to: "users#search"

  get "my_portfolio", to: "users#my_portfolio"
  get "following", to: "users#following"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, presence: true, :on => :create
  validates :ticker,
            presence: true,
            uniqueness: { case_sensitive: false },
            :on => :create

  before_validation { self.ticker = ticker.upcase }

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    begin client.quote(ticker_symbol)
      stock = Stock.check_db(ticker_symbol.upcase)

      if stock.present?
        stock.update_price
      else
        Stock.create(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
      end
    rescue => exception
      nil
    end
  end

  def self.check_db(ticker_symbol)
    Stock.find_by(ticker: ticker_symbol)
  end

  def update_price
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    stock.update(last_price: client.price(self.ticker))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(ticker: ticker_symbol).exists?
  end

  def under_stock_limit?
    stocks.count <= 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = ( first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.matches(keyword, param)
    where("#{keyword} like ?", "%#{param}%")
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_freind_with?(friend_id)
    !self.friends.where(id: friend_id).exists?
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def logged_in?
    redirect_to root_url unless current_user.blank?
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend: friend)
    if current_user.save
      flash.now[:notice] = "Following #{friend.full_name}"
    else
      flash.now[:notice] = "There was something wrong"
    end
    redirect_to following_path
  end

  def destroy
    friend = User.find(params[:id])
    friendship = Friendship.find_by(friend_id: friend.id)
    friendship.destroy
    flash.now[:notice] = "#{friend.full_name} was successfully removed"
    redirect_to following_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: "stocks/result", status: :ok }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: "stocks/result" }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: "stocks/result" }
      end
    end
  end

  def update
    stock = Stock.update_price(params[:id])
    if stock.update(params.permit(:id))
      flash.now[:notice] = "#{stock} updated"
      redirect_to my_portfolio_path
    else
      flash.now[:alert] = "Error! #{stock} update failed!"
      redirect_to my_portfolio_path
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.new_lookup(params[:ticker])
    # if stock.blank?
    #   stock = Stock.new_lookup(params[:ticker])
    #   stock.save
    # end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash.now[:notice] = "#{stock.name} was successfully added to stocks portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.find_by(stock_id: stock.id)
    user_stock.destroy
    flash.now[:notice] = "#{user_stock.stock.name} was successfully removed"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def following
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_bootstrap_views_helper.rb
module DeviseBootstrapViewsHelper
  def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |message| content_tag(:li, message) }.join
    sentence = I18n.t(
      'errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase
    )

    html = <<-HTML
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="alert-heading">#{sentence}</h4>
      <ul class="mb-0">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Firstname</th>
          <th scope="col">Lastname</th>
          <th scope="col">E-mail</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
        <tr>
          <th scope="row"><%= friend.first_name %></th>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td>
            <%= link_to "View", user_path(friend.id), class:"btn btn-sm btn-success" %>
            <%= link_to "Unfollow", friendship_path(friend), method: :delete,
                data: {confirm: "Are you sure?"} ,class:"btn btn-sm btn-warning" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_datetime.html.erb
<div class="row">
  <div class="col-">
    <div class="badge bg-dark text-light time-block"> Date Time
      <span class="badge bg-secondary"><%= Time.zone.now.strftime("%k:%M %d-%b-%y") %></span>
      EST
    </div>
  </div>
</div>

app/views/layouts/_message.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "FinanceTracker", root_path, class:"navbar-brand" %>
    <% if current_user %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= "active" if request.path == my_portfolio_path %>" >
          <%= link_to my_portfolio_path, class:"nav-link" do %>
            <%= fa_icon "bookmark" %> Portfolio  
          <% end %>
        </li>
        <li class="nav-item <%= "active" if request.path == following_path %>" >
          <%= link_to following_path, class:"nav-link" do %>
            <%= fa_icon "group" %> Following  
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to edit_user_registration_path, class:"dropdown-item" do %>
              <%= fa_icon "edit" %> Edit
            <% end %>
          </div>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item user-name">
          <%= fa_icon "user-circle-o" %> <%= current_user.full_name %>
        </li>
          <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete ,class: "btn btn-sm btn-outline-danger logout-button" do %>
                Logout <%= fa_icon "sign-out" %>
              <% end %>
          </li>
        </ul>
        <% else %>
        <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "btn btn-sm btn-outline-primary logout-button" do %>
            Register <%= fa_icon "user-plus" %> 
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "btn btn-sm btn-outline-primary logout-button" do %>
            Login <%= fa_icon "arrow-right" %> 
          <% end %>
        </li>
      </ul>
    </div>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Finance Tracker application</h1>

<div class="search-area">
  <div class="row">
    <div class="col-7">
      <h3>Search Stocks</h3>
    </div>
    <div class="col">
        <div id="date-time">
        </div>
    </div>
  </div>

  <%= render 'stocks/search_bar'%>

<div id="results">
</div>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Updated (EST)</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td><small><%= stock.updated_at.strftime("%Y-%m-%d %H:%M") %></small></td>
          <td><%= link_to "Update", stock_path(stock),
                  method: :put, class:"btn btn-sm btn-success" %>
              <% if current_user.can_track_stock?(stock.ticker) %>
              <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: stock.ticker),
                  method: :post, class:"btn btn-sm btn-success" %>
              <% elsif current_user != @user %>
                <span class="badge badge-secondary text-light">
                  Alreay tracking
                  <% if !current_user.under_stock_limit? %>
                    10 stocks
                  <% end %>
                  <% if current_user.stock_already_tracked?(stock.ticker) %>
                    this stock
                  <% end %>
                </span>
              <% else %>
                <%= link_to "Remove", user_stock_path(stock),
                    method: :delete, data: {confirm: "Are you sure?"} ,class:"btn btn-sm btn-warning" %>
              <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stocks/_result.html.erb
<div class="results-block">
  <%= render "layouts/messages" %>
</div>

<% if @stock %>
<div class="card card-header results-block">
  <strong>Symbol: </strong> <%= @stock.ticker %>
  <strong>Name: </strong> <%= @stock.name %>
  <strong>Price: </strong> <%= @stock.last_price %>
  <% if current_user %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
    <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker),
        method: :post, class:"btn btn-sm btn-success" %>
    <% else %>
      <span class="badge badge-secondary text-warning">
        Alreay tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/stocks/_result.js.erb
document.querySelector('#results').innerHTML = "<%= escape_javascript( render 'stocks/result.html' ) %>"
document.querySelector('#date-time').innerHTML = '<%= j render 'layouts/datetime.html' %>'

app/views/stocks/_search_bar.html.erb
  <%= form_tag search_stock_path, remote: true, method: :get do %>
  <div class="form-group row">
    <div class="col-sm-9 no-right-padding">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol (ex: TSM, TSLA, FB, AAPL...)", autofocus: true, class: "form-control form-control-lg" %>
    </div>
    <div class="col-sm-3 no-left-padding">
      <%= button_tag type: :submit, class: "btn btn-success" do %>
      <%= fa_icon "search 2x" %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render "layouts/messages" %>
</div>

<% if @friends %>
<div class="card card-header results-block">
<table class="col-md-12">
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><strong>Name: </strong> <%= friend.full_name %></td>  
        <td><strong>E-mail: </strong> <%= friend.email %></td>
        <td><strong>Profile: </strong> <%= link_to "View", user_path(friend.id),
                                          class:"btn btn-sm btn-outline-success" %>
            <% if current_user.not_freind_with?(friend.id) %>
            <%= link_to "Follow?", friendships_path(user: current_user, friend: friend),
                method: :post, class:"btn btn-sm btn-outline-success" %>
            <% else %>
              <span class="badge badge-secondary text-warning">
                already followed
              </span>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  
</div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/following.html.erb
<h1>Following</h1>

<div class="search-area">
  <h3>Search Users</h3>
  <%= form_tag search_user_path, remote: true, method: :get do %>
  <div class="form-group row">

    <div class="col-sm-9 no-right-padding">
      <%= text_field_tag :friend, params[:friend], placeholder: "Name or E-mail", autofocus: true, class: "form-control form-control-lg" %>
    </div>
    <div class="col-sm-3 no-left-padding">
      <%= button_tag type: :submit, class: "btn btn-success" do %>
      <%= fa_icon "search 2x" %>
      <% end %>
    </div>

  </div>
  <% end %>
</div>

<div id="friend-results">
</div>

<% if !@friends.empty? %>
  <%= render "friends/list" %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<div class="search-area">
  <div class="row">
    <div class="col-7">
      <h3>Search Stocks</h3>
    </div>
    <div class="col">
        <div id="date-time">
        </div>
    </div>
  </div>

  <%= render 'stocks/search_bar'%>

<div id="results">
</div>

<% if !@tracked_stocks.empty? %>
  <%= render "stocks/list" %>
<% end %>

app/views/users/show.html.erb
<h1>Users Details</h1>

<div class="card card-header results-block">
<table class="col-md-12">
  <tbody>
    <tr>
      <td><strong>Name: </strong> <%= @user.full_name %></td>  
      <td><strong>E-mail: </strong> <%= @user.email %></td>
      <td>
          <% if current_user.not_freind_with?(@user.id) %>
          <%= link_to "Follow?", friendships_path(friend: @user),
              method: :post, class:"btn btn-sm btn-outline-success" %>
          <% else %>
            <span class="badge badge-secondary text-warning">
              already followed
            </span>
          <% end %>
      </td>
    </tr>
  </tbody>
</table>
</div>


<% if !@tracked_stocks.empty? %>
  <%= render "stocks/list" %>
<% else %>
  <p class='lead text-primary'>This user is not tracking any stocks</p>
<% end %>
<%= link_to 'Back', following_path, class: "btn btn-primary" %>